# Site settings
title: Best Buy @ UDE Hackathon
email: developer@bestbuy.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/ude-hack" # the subpath of your site, e.g. /blog/
url: "https://bestbuyapis.github.io/use-hack" # the base hostname & protocol for your site
twitter_username: BBYopen
github_username:  BestBuyAPIs

# Build settings
markdown: kramdown
exclude: [vendor]
